<?php
class snowbot
 {
      const API_KEY="https://api.telegram.org/bot1889200390:AAELafIDIYH_e502newEeWZkR-M8pO6Y10g";
      
      public function setWebhook($url)
      {
      return $this->request('setWebhook', [
        'url'=> $url
        ]);
      }
      public function request($method, $data)
      
      {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        
        $url=self::API_KEY.$method;
        
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
        
        $headers = array();
        $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        
        return $result;
      }
   
    public function sendMessage($chat_id, $text)
    { 
      return $this->request("sendMessage", [
        'chat_id'->$chat_id,
        'text'->$text
        ]);
    }
    
    public function updates()
    {
      $update=json_decode(file_get_contents("php://input"), ture);
      return $update->message;
    }
 }
    
    $bot= new snowbot();
   echo $bot->setWebhook("https://snowbot.000webhostapp.com");

$data=$bot->Updates();
$text=$data->text;
$chat_id=$data->chat->id;
    

if ($text == "/start"){
$bot->ask('Show phone', function (Answer $answer) use ($bot) {
    $bot->reply('Handled!');
}, ['reply_markup' => json_encode([
    'keyboard' => [[['text' => 'Show phone', 'request_contact' => true]]]
])]);
}
?>